// function Fonction GetMessage 
// Generated by Structorizer 3.25-01 

// TODO: Revise the return type and declare the parameters. 
void Affolter()
{
	// TODO: declare your variables here: 
	// reçue 
	
	Entrées: pointeur: pData;
	Sorties: uint8_t;
	Variables:;
	static entier nonsigné codé 8bits: i == 10;
	entier nonsigné codé 8bits: lsb == 0; NbCharToRead == 0;
	entier signé codé 8bits: debut == 0;;
	entier nonsigné codé 16bits: crc == 0; ValCrc16 == 0xFFFF;
	S_pwmSettings: pDataTemporaire;
	Sauvegarder la taille du message dans NbCharToRead;
	if (SI(NbCharToRead >= MESS_SIZE))
	{
		Récupérer la valeur reçue en la sauvegardant à l'adresse de debut;
		if (SI(debut == 0xAA))
		{
			Récupérer la valeur reçue en la sauvegardant à l'adresse de vitesse dans pDataTemporaire;
			Récupérer la valeur reçue en la sauvegardant à l'adresse de angle dans pDataTemporaire;
			Récupérer la valeur reçue en la sauvegardant à l'adresse de crc;
			Décaler crc à gauche de 8;
			Récupérer la valeur reçue en la sauvegardant à l'adresse de lsb;
			crc == crc + lsb;
			ValCrc16 == updateCRC16(ValCrc16, 0xAA);
			ValCrc16 == updateCRC16(ValCrc16, vitesse de pDataTemporaire);
			ValCrc16 == updateCRC16(ValCrc16, angle de pDataTemporaire);
			if (SI(crc == ValCrc16))
			{
				pData == pDataTemporaire;
				i == 0;
				Retourner un 1;
			}
		}
	}
	if (SI(i >= 9))
	{
		Retourner un 0;
	}
	else
	{
		Incrémenter i;
		Retourner un 1;
	}
}